
package endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExternalSystemAndMockService", targetNamespace = "http://placeservice/", wsdlLocation = "http://localhost:8080/mSoapServer/ExternalSystemAndMock?wsdl")
public class ExternalSystemAndMockService
    extends Service
{

    private final static URL EXTERNALSYSTEMANDMOCKSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXTERNALSYSTEMANDMOCKSERVICE_EXCEPTION;
    private final static QName EXTERNALSYSTEMANDMOCKSERVICE_QNAME = new QName("http://placeservice/", "ExternalSystemAndMockService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mSoapServer/ExternalSystemAndMock?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERNALSYSTEMANDMOCKSERVICE_WSDL_LOCATION = url;
        EXTERNALSYSTEMANDMOCKSERVICE_EXCEPTION = e;
    }

    public ExternalSystemAndMockService() {
        super(__getWsdlLocation(), EXTERNALSYSTEMANDMOCKSERVICE_QNAME);
    }

    public ExternalSystemAndMockService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERNALSYSTEMANDMOCKSERVICE_QNAME, features);
    }

    public ExternalSystemAndMockService(URL wsdlLocation) {
        super(wsdlLocation, EXTERNALSYSTEMANDMOCKSERVICE_QNAME);
    }

    public ExternalSystemAndMockService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERNALSYSTEMANDMOCKSERVICE_QNAME, features);
    }

    public ExternalSystemAndMockService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalSystemAndMockService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExternalSystemAndMock
     */
    @WebEndpoint(name = "ExternalSystemAndMockPort")
    public ExternalSystemAndMock getExternalSystemAndMockPort() {
        return super.getPort(new QName("http://placeservice/", "ExternalSystemAndMockPort"), ExternalSystemAndMock.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalSystemAndMock
     */
    @WebEndpoint(name = "ExternalSystemAndMockPort")
    public ExternalSystemAndMock getExternalSystemAndMockPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://placeservice/", "ExternalSystemAndMockPort"), ExternalSystemAndMock.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERNALSYSTEMANDMOCKSERVICE_EXCEPTION!= null) {
            throw EXTERNALSYSTEMANDMOCKSERVICE_EXCEPTION;
        }
        return EXTERNALSYSTEMANDMOCKSERVICE_WSDL_LOCATION;
    }

}
