
package endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExternalSystemService", targetNamespace = "http://placeservice/", wsdlLocation = "http://localhost:8080/mSoapServer/ExternalSystem?wsdl")
public class ExternalSystemService
    extends Service
{

    private final static URL EXTERNALSYSTEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXTERNALSYSTEMSERVICE_EXCEPTION;
    private final static QName EXTERNALSYSTEMSERVICE_QNAME = new QName("http://placeservice/", "ExternalSystemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mSoapServer/ExternalSystem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXTERNALSYSTEMSERVICE_WSDL_LOCATION = url;
        EXTERNALSYSTEMSERVICE_EXCEPTION = e;
    }

    public ExternalSystemService() {
        super(__getWsdlLocation(), EXTERNALSYSTEMSERVICE_QNAME);
    }

    public ExternalSystemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXTERNALSYSTEMSERVICE_QNAME, features);
    }

    public ExternalSystemService(URL wsdlLocation) {
        super(wsdlLocation, EXTERNALSYSTEMSERVICE_QNAME);
    }

    public ExternalSystemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXTERNALSYSTEMSERVICE_QNAME, features);
    }

    public ExternalSystemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalSystemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExternalSystem
     */
    @WebEndpoint(name = "ExternalSystemPort")
    public ExternalSystem getExternalSystemPort() {
        return super.getPort(new QName("http://placeservice/", "ExternalSystemPort"), ExternalSystem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalSystem
     */
    @WebEndpoint(name = "ExternalSystemPort")
    public ExternalSystem getExternalSystemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://placeservice/", "ExternalSystemPort"), ExternalSystem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXTERNALSYSTEMSERVICE_EXCEPTION!= null) {
            throw EXTERNALSYSTEMSERVICE_EXCEPTION;
        }
        return EXTERNALSYSTEMSERVICE_WSDL_LOCATION;
    }

}
